apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}
  labels:
    app: {{ $.Chart.Name }}
    release: {{ $.Release.Name }}
spec:
  replicas: {{ $.Values.replicas }}
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ $.Chart.Name }}
      release: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $.Chart.Name }}
        release: {{ $.Release.Name }}
    spec:
      serviceAccountName: {{ $.Release.Name }}
      containers:
      - name: {{ $.Release.Name }}
        image: "pickledish/witw:{{ $.Chart.AppVersion }}"
        imagePullPolicy: Always
        # this is what starts the docker image in the appropriate mode
        command:
        - {{ required "need mode-specific values file" $.Values.command }}
        env:
        {{- range $name, $value := $.Values.environment }}
        - name: "{{ $name }}"
          value: "{{ $value }}"
        {{- end }}
        # equivalent to "docker run --expose", so no need for EXPOSE in dockerfile
        ports:
        - containerPort: {{ $.Values.service.port }}
          protocol: {{ $.Values.service.protocol }}
        {{- if $.Values.resources }}
        resources:
          requests:
            cpu: "{{ $.Values.resources.cpu }}"
            memory: "{{ $.Values.resources.memory }}"
          limits:
            cpu: "{{ $.Values.resources.cpu }}"
            memory: "{{ $.Values.resources.memory }}"
        {{- end }}
